version: "3.7"

services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      TYPE: "PAPER"
    ports:
      - "25565:25565"
    volumes:
      - /mnt/data/kevin-minecraft:/data
